#!/usr/bin/env python3
"""Generate test.asm: one timing measurement per instruction sequence.

Each measurement starts at a fixed raster position: after VSYNC the Gate
Array interrupt counter is reset, and EI/HALT waits for the interrupt 52
lines later (the handler returns with interrupts still disabled). It then
counts iterations of
    <sequence> ; INC DE ; IN A,(C) ; RRA ; JR cc
until the next VSYNC starts. The count is very sensitive to the sequence's
duration in microseconds, to when IN samples VSYNC, and to interrupt
timing. Counts are stored as 16-bit words at RESULTS + 2*i.

Sequences must preserve B (the PPI port), DE (the counter), HL, IX
(scratch pointers) and SP.
"""

SEQUENCES = [
    "nop",
    "nop : nop",
    "ld a,(hl)",
    "ld (hl),a",
    "inc hl : dec hl",
    "add iy,iy",
    "push hl : pop hl",
    "ex (sp),hl : ex (sp),hl",
    "ld a,(ix+0)",
    "ld (ix+0),a",
    "ld (ix+1),0",
    "inc (hl)",
    "bit 0,(ix+0)",
    "set 0,(ix+0)",
    "srl (ix+1)",
    "rld",
    "out (c),a",
    "in a,(c)",
    "call sub_ret",
    "rst 030h",
    "jp $+3",
    "jr $+2",
    "ex af,af' : ex af,af'",
    "exx : exx",
    "neg",
    "daa",
    "ld a,i",
    "ld a,r",
    "ld i,a",
    "ld a,ixh",
    "ld (0A000h),a",
    "ld a,(0A000h)",
    "ld iy,(0A000h)",
    "ld (0A000h),iy",
    "exx : ldi : exx",
    "exx : cpi : exx",
    "exx : ldd : exx",
    "rlca",
    "rl (hl)",
    "ld sp,hl : ld sp,0BF00h",
    "im 1",
    "di",
    "inc iy",
    "add hl,de : sbc hl,de",
    "exx : outi : inc b : exx",
    "exx : ini : inc b : exx",
]


def main() -> None:
    out = [
        "; Generated by gen.py. Instruction timing measured against VSYNC.",
        'include "../../../lib/prelude.asm"',
        "",
        "irq_handler:",
        "        ret",
        "",
        "        org 030h",
        "        ret",
        "        org 0100h",
        "sub_ret:",
        "        ret",
        "",
        "main:",
        "        ld sp,0BF00h",
        "        ld hl,09800h   ; clear the scratch area",
        "        ld de,09801h",
        "        ld bc,007FFh",
        "        ld (hl),0",
        "        ldir",
        "        ld hl,09800h",
        "        ld ix,09800h",
        "        exx",
        "        ld hl,09A00h",
        "        ld de,09C00h",
        "        ld bc,07FFFh   ; alternate BC: block ops never reach zero, OUTI hits port 7F (pen select, harmless)",
        "        exx",
    ]
    for i, seq in enumerate(SEQUENCES):
        body = [s.strip() for s in seq.split(":")]
        out.append(f"; [{i}] {seq}")
        out.append("        call wait_vsync")
        out.append("        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter")
        out.append("        out (c),c")
        out.append("        ei")
        out.append("        halt")
        out.append("        ld b,0F5h")
        out.append("        ld de,0")
        for phase, cond in (("a", "c"), ("b", "nc")):
            out.append(f"t{i}{phase}:")
            out += [f"        {s}" for s in body]
            out += [
                "        inc de",
                "        in a,(c)",
                "        rra",
                f"        jr {cond},t{i}{phase}",
            ]
        out.append(f"        ld (RESULTS+{2 * i}),de")
    out += ["done:", "        jr done", ""]
    with open("test.asm", "w") as fh:
        fh.write("\n".join(out))
    print(f"{len(SEQUENCES)} sequences")


if __name__ == "__main__":
    main()
