; Generated by gen.py. Instruction timing measured against VSYNC.
include "../../../lib/prelude.asm"

irq_handler:
        ret

        org 030h
        ret
        org 0100h
sub_ret:
        ret

main:
        ld sp,0BF00h
        ld hl,09800h   ; clear the scratch area
        ld de,09801h
        ld bc,007FFh
        ld (hl),0
        ldir
        ld hl,09800h
        ld ix,09800h
        exx
        ld hl,09A00h
        ld de,09C00h
        ld bc,07FFFh   ; alternate BC: block ops never reach zero, OUTI hits port 7F (pen select, harmless)
        exx
; [0] nop
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t0a:
        nop
        inc de
        in a,(c)
        rra
        jr c,t0a
t0b:
        nop
        inc de
        in a,(c)
        rra
        jr nc,t0b
        ld (RESULTS+0),de
; [1] nop : nop
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t1a:
        nop
        nop
        inc de
        in a,(c)
        rra
        jr c,t1a
t1b:
        nop
        nop
        inc de
        in a,(c)
        rra
        jr nc,t1b
        ld (RESULTS+2),de
; [2] ld a,(hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t2a:
        ld a,(hl)
        inc de
        in a,(c)
        rra
        jr c,t2a
t2b:
        ld a,(hl)
        inc de
        in a,(c)
        rra
        jr nc,t2b
        ld (RESULTS+4),de
; [3] ld (hl),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t3a:
        ld (hl),a
        inc de
        in a,(c)
        rra
        jr c,t3a
t3b:
        ld (hl),a
        inc de
        in a,(c)
        rra
        jr nc,t3b
        ld (RESULTS+6),de
; [4] inc hl : dec hl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t4a:
        inc hl
        dec hl
        inc de
        in a,(c)
        rra
        jr c,t4a
t4b:
        inc hl
        dec hl
        inc de
        in a,(c)
        rra
        jr nc,t4b
        ld (RESULTS+8),de
; [5] add iy,iy
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t5a:
        add iy,iy
        inc de
        in a,(c)
        rra
        jr c,t5a
t5b:
        add iy,iy
        inc de
        in a,(c)
        rra
        jr nc,t5b
        ld (RESULTS+10),de
; [6] push hl : pop hl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t6a:
        push hl
        pop hl
        inc de
        in a,(c)
        rra
        jr c,t6a
t6b:
        push hl
        pop hl
        inc de
        in a,(c)
        rra
        jr nc,t6b
        ld (RESULTS+12),de
; [7] ex (sp),hl : ex (sp),hl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t7a:
        ex (sp),hl
        ex (sp),hl
        inc de
        in a,(c)
        rra
        jr c,t7a
t7b:
        ex (sp),hl
        ex (sp),hl
        inc de
        in a,(c)
        rra
        jr nc,t7b
        ld (RESULTS+14),de
; [8] ld a,(ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t8a:
        ld a,(ix+0)
        inc de
        in a,(c)
        rra
        jr c,t8a
t8b:
        ld a,(ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t8b
        ld (RESULTS+16),de
; [9] ld (ix+0),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t9a:
        ld (ix+0),a
        inc de
        in a,(c)
        rra
        jr c,t9a
t9b:
        ld (ix+0),a
        inc de
        in a,(c)
        rra
        jr nc,t9b
        ld (RESULTS+18),de
; [10] ld (ix+1),0
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t10a:
        ld (ix+1),0
        inc de
        in a,(c)
        rra
        jr c,t10a
t10b:
        ld (ix+1),0
        inc de
        in a,(c)
        rra
        jr nc,t10b
        ld (RESULTS+20),de
; [11] inc (hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t11a:
        inc (hl)
        inc de
        in a,(c)
        rra
        jr c,t11a
t11b:
        inc (hl)
        inc de
        in a,(c)
        rra
        jr nc,t11b
        ld (RESULTS+22),de
; [12] bit 0,(ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t12a:
        bit 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr c,t12a
t12b:
        bit 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t12b
        ld (RESULTS+24),de
; [13] set 0,(ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t13a:
        set 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr c,t13a
t13b:
        set 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t13b
        ld (RESULTS+26),de
; [14] srl (ix+1)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t14a:
        srl (ix+1)
        inc de
        in a,(c)
        rra
        jr c,t14a
t14b:
        srl (ix+1)
        inc de
        in a,(c)
        rra
        jr nc,t14b
        ld (RESULTS+28),de
; [15] rld
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t15a:
        rld
        inc de
        in a,(c)
        rra
        jr c,t15a
t15b:
        rld
        inc de
        in a,(c)
        rra
        jr nc,t15b
        ld (RESULTS+30),de
; [16] out (c),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t16a:
        out (c),a
        inc de
        in a,(c)
        rra
        jr c,t16a
t16b:
        out (c),a
        inc de
        in a,(c)
        rra
        jr nc,t16b
        ld (RESULTS+32),de
; [17] in a,(c)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t17a:
        in a,(c)
        inc de
        in a,(c)
        rra
        jr c,t17a
t17b:
        in a,(c)
        inc de
        in a,(c)
        rra
        jr nc,t17b
        ld (RESULTS+34),de
; [18] call sub_ret
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t18a:
        call sub_ret
        inc de
        in a,(c)
        rra
        jr c,t18a
t18b:
        call sub_ret
        inc de
        in a,(c)
        rra
        jr nc,t18b
        ld (RESULTS+36),de
; [19] rst 030h
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t19a:
        rst 030h
        inc de
        in a,(c)
        rra
        jr c,t19a
t19b:
        rst 030h
        inc de
        in a,(c)
        rra
        jr nc,t19b
        ld (RESULTS+38),de
; [20] jp $+3
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t20a:
        jp $+3
        inc de
        in a,(c)
        rra
        jr c,t20a
t20b:
        jp $+3
        inc de
        in a,(c)
        rra
        jr nc,t20b
        ld (RESULTS+40),de
; [21] jr $+2
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t21a:
        jr $+2
        inc de
        in a,(c)
        rra
        jr c,t21a
t21b:
        jr $+2
        inc de
        in a,(c)
        rra
        jr nc,t21b
        ld (RESULTS+42),de
; [22] ex af,af' : ex af,af'
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t22a:
        ex af,af'
        ex af,af'
        inc de
        in a,(c)
        rra
        jr c,t22a
t22b:
        ex af,af'
        ex af,af'
        inc de
        in a,(c)
        rra
        jr nc,t22b
        ld (RESULTS+44),de
; [23] exx : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t23a:
        exx
        exx
        inc de
        in a,(c)
        rra
        jr c,t23a
t23b:
        exx
        exx
        inc de
        in a,(c)
        rra
        jr nc,t23b
        ld (RESULTS+46),de
; [24] neg
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t24a:
        neg
        inc de
        in a,(c)
        rra
        jr c,t24a
t24b:
        neg
        inc de
        in a,(c)
        rra
        jr nc,t24b
        ld (RESULTS+48),de
; [25] daa
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t25a:
        daa
        inc de
        in a,(c)
        rra
        jr c,t25a
t25b:
        daa
        inc de
        in a,(c)
        rra
        jr nc,t25b
        ld (RESULTS+50),de
; [26] ld a,i
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t26a:
        ld a,i
        inc de
        in a,(c)
        rra
        jr c,t26a
t26b:
        ld a,i
        inc de
        in a,(c)
        rra
        jr nc,t26b
        ld (RESULTS+52),de
; [27] ld a,r
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t27a:
        ld a,r
        inc de
        in a,(c)
        rra
        jr c,t27a
t27b:
        ld a,r
        inc de
        in a,(c)
        rra
        jr nc,t27b
        ld (RESULTS+54),de
; [28] ld i,a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t28a:
        ld i,a
        inc de
        in a,(c)
        rra
        jr c,t28a
t28b:
        ld i,a
        inc de
        in a,(c)
        rra
        jr nc,t28b
        ld (RESULTS+56),de
; [29] ld a,ixh
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t29a:
        ld a,ixh
        inc de
        in a,(c)
        rra
        jr c,t29a
t29b:
        ld a,ixh
        inc de
        in a,(c)
        rra
        jr nc,t29b
        ld (RESULTS+58),de
; [30] ld (0A000h),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t30a:
        ld (0A000h),a
        inc de
        in a,(c)
        rra
        jr c,t30a
t30b:
        ld (0A000h),a
        inc de
        in a,(c)
        rra
        jr nc,t30b
        ld (RESULTS+60),de
; [31] ld a,(0A000h)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t31a:
        ld a,(0A000h)
        inc de
        in a,(c)
        rra
        jr c,t31a
t31b:
        ld a,(0A000h)
        inc de
        in a,(c)
        rra
        jr nc,t31b
        ld (RESULTS+62),de
; [32] ld iy,(0A000h)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t32a:
        ld iy,(0A000h)
        inc de
        in a,(c)
        rra
        jr c,t32a
t32b:
        ld iy,(0A000h)
        inc de
        in a,(c)
        rra
        jr nc,t32b
        ld (RESULTS+64),de
; [33] ld (0A000h),iy
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t33a:
        ld (0A000h),iy
        inc de
        in a,(c)
        rra
        jr c,t33a
t33b:
        ld (0A000h),iy
        inc de
        in a,(c)
        rra
        jr nc,t33b
        ld (RESULTS+66),de
; [34] exx : ldi : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t34a:
        exx
        ldi
        exx
        inc de
        in a,(c)
        rra
        jr c,t34a
t34b:
        exx
        ldi
        exx
        inc de
        in a,(c)
        rra
        jr nc,t34b
        ld (RESULTS+68),de
; [35] exx : cpi : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t35a:
        exx
        cpi
        exx
        inc de
        in a,(c)
        rra
        jr c,t35a
t35b:
        exx
        cpi
        exx
        inc de
        in a,(c)
        rra
        jr nc,t35b
        ld (RESULTS+70),de
; [36] exx : ldd : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t36a:
        exx
        ldd
        exx
        inc de
        in a,(c)
        rra
        jr c,t36a
t36b:
        exx
        ldd
        exx
        inc de
        in a,(c)
        rra
        jr nc,t36b
        ld (RESULTS+72),de
; [37] rlca
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t37a:
        rlca
        inc de
        in a,(c)
        rra
        jr c,t37a
t37b:
        rlca
        inc de
        in a,(c)
        rra
        jr nc,t37b
        ld (RESULTS+74),de
; [38] rl (hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t38a:
        rl (hl)
        inc de
        in a,(c)
        rra
        jr c,t38a
t38b:
        rl (hl)
        inc de
        in a,(c)
        rra
        jr nc,t38b
        ld (RESULTS+76),de
; [39] ld sp,hl : ld sp,0BF00h
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t39a:
        ld sp,hl
        ld sp,0BF00h
        inc de
        in a,(c)
        rra
        jr c,t39a
t39b:
        ld sp,hl
        ld sp,0BF00h
        inc de
        in a,(c)
        rra
        jr nc,t39b
        ld (RESULTS+78),de
; [40] im 1
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t40a:
        im 1
        inc de
        in a,(c)
        rra
        jr c,t40a
t40b:
        im 1
        inc de
        in a,(c)
        rra
        jr nc,t40b
        ld (RESULTS+80),de
; [41] di
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t41a:
        di
        inc de
        in a,(c)
        rra
        jr c,t41a
t41b:
        di
        inc de
        in a,(c)
        rra
        jr nc,t41b
        ld (RESULTS+82),de
; [42] inc iy
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t42a:
        inc iy
        inc de
        in a,(c)
        rra
        jr c,t42a
t42b:
        inc iy
        inc de
        in a,(c)
        rra
        jr nc,t42b
        ld (RESULTS+84),de
; [43] add hl,de : sbc hl,de
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t43a:
        add hl,de
        sbc hl,de
        inc de
        in a,(c)
        rra
        jr c,t43a
t43b:
        add hl,de
        sbc hl,de
        inc de
        in a,(c)
        rra
        jr nc,t43b
        ld (RESULTS+86),de
; [44] exx : outi : inc b : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t44a:
        exx
        outi
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr c,t44a
t44b:
        exx
        outi
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr nc,t44b
        ld (RESULTS+88),de
; [45] exx : ini : inc b : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t45a:
        exx
        ini
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr c,t45a
t45b:
        exx
        ini
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr nc,t45b
        ld (RESULTS+90),de
done:
        jr done
