; Generated by gen.py. Instruction timing measured against VSYNC.
include "../../../lib/prelude.asm"

irq_handler:
        ret

        org 030h
        ret
        org 0100h
sub_ret:
        ret
sub_retz_taken:
        xor a
        ret z
        ret
sub_retz_not:
        or 1
        ret z
        ret

main:
        ld sp,0BF00h
        ld hl,09800h   ; clear the scratch area
        ld de,09801h
        ld bc,007FFh
        ld (hl),0
        ldir
        ld hl,09800h
        ld ix,09800h
        exx
        ld hl,09A00h
        ld de,09C00h
        ld bc,07FFFh   ; alternate BC: block ops never reach zero, OUTI hits port 7F (pen select, harmless)
        exx
; [0] nop
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t0a:
        nop
        inc de
        in a,(c)
        rra
        jr c,t0a
t0b:
        nop
        inc de
        in a,(c)
        rra
        jr nc,t0b
        ld (RESULTS+0),de
; [1] nop : nop
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t1a:
        nop
        nop
        inc de
        in a,(c)
        rra
        jr c,t1a
t1b:
        nop
        nop
        inc de
        in a,(c)
        rra
        jr nc,t1b
        ld (RESULTS+2),de
; [2] ld a,(hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t2a:
        ld a,(hl)
        inc de
        in a,(c)
        rra
        jr c,t2a
t2b:
        ld a,(hl)
        inc de
        in a,(c)
        rra
        jr nc,t2b
        ld (RESULTS+4),de
; [3] ld (hl),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t3a:
        ld (hl),a
        inc de
        in a,(c)
        rra
        jr c,t3a
t3b:
        ld (hl),a
        inc de
        in a,(c)
        rra
        jr nc,t3b
        ld (RESULTS+6),de
; [4] inc hl : dec hl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t4a:
        inc hl
        dec hl
        inc de
        in a,(c)
        rra
        jr c,t4a
t4b:
        inc hl
        dec hl
        inc de
        in a,(c)
        rra
        jr nc,t4b
        ld (RESULTS+8),de
; [5] add iy,iy
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t5a:
        add iy,iy
        inc de
        in a,(c)
        rra
        jr c,t5a
t5b:
        add iy,iy
        inc de
        in a,(c)
        rra
        jr nc,t5b
        ld (RESULTS+10),de
; [6] push hl : pop hl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t6a:
        push hl
        pop hl
        inc de
        in a,(c)
        rra
        jr c,t6a
t6b:
        push hl
        pop hl
        inc de
        in a,(c)
        rra
        jr nc,t6b
        ld (RESULTS+12),de
; [7] ex (sp),hl : ex (sp),hl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t7a:
        ex (sp),hl
        ex (sp),hl
        inc de
        in a,(c)
        rra
        jr c,t7a
t7b:
        ex (sp),hl
        ex (sp),hl
        inc de
        in a,(c)
        rra
        jr nc,t7b
        ld (RESULTS+14),de
; [8] ld a,(ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t8a:
        ld a,(ix+0)
        inc de
        in a,(c)
        rra
        jr c,t8a
t8b:
        ld a,(ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t8b
        ld (RESULTS+16),de
; [9] ld (ix+0),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t9a:
        ld (ix+0),a
        inc de
        in a,(c)
        rra
        jr c,t9a
t9b:
        ld (ix+0),a
        inc de
        in a,(c)
        rra
        jr nc,t9b
        ld (RESULTS+18),de
; [10] ld (ix+1),0
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t10a:
        ld (ix+1),0
        inc de
        in a,(c)
        rra
        jr c,t10a
t10b:
        ld (ix+1),0
        inc de
        in a,(c)
        rra
        jr nc,t10b
        ld (RESULTS+20),de
; [11] inc (hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t11a:
        inc (hl)
        inc de
        in a,(c)
        rra
        jr c,t11a
t11b:
        inc (hl)
        inc de
        in a,(c)
        rra
        jr nc,t11b
        ld (RESULTS+22),de
; [12] bit 0,(ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t12a:
        bit 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr c,t12a
t12b:
        bit 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t12b
        ld (RESULTS+24),de
; [13] set 0,(ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t13a:
        set 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr c,t13a
t13b:
        set 0,(ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t13b
        ld (RESULTS+26),de
; [14] srl (ix+1)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t14a:
        srl (ix+1)
        inc de
        in a,(c)
        rra
        jr c,t14a
t14b:
        srl (ix+1)
        inc de
        in a,(c)
        rra
        jr nc,t14b
        ld (RESULTS+28),de
; [15] rld
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t15a:
        rld
        inc de
        in a,(c)
        rra
        jr c,t15a
t15b:
        rld
        inc de
        in a,(c)
        rra
        jr nc,t15b
        ld (RESULTS+30),de
; [16] out (c),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t16a:
        out (c),a
        inc de
        in a,(c)
        rra
        jr c,t16a
t16b:
        out (c),a
        inc de
        in a,(c)
        rra
        jr nc,t16b
        ld (RESULTS+32),de
; [17] in a,(c)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t17a:
        in a,(c)
        inc de
        in a,(c)
        rra
        jr c,t17a
t17b:
        in a,(c)
        inc de
        in a,(c)
        rra
        jr nc,t17b
        ld (RESULTS+34),de
; [18] call sub_ret
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t18a:
        call sub_ret
        inc de
        in a,(c)
        rra
        jr c,t18a
t18b:
        call sub_ret
        inc de
        in a,(c)
        rra
        jr nc,t18b
        ld (RESULTS+36),de
; [19] rst 030h
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t19a:
        rst 030h
        inc de
        in a,(c)
        rra
        jr c,t19a
t19b:
        rst 030h
        inc de
        in a,(c)
        rra
        jr nc,t19b
        ld (RESULTS+38),de
; [20] jp $+3
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t20a:
        jp $+3
        inc de
        in a,(c)
        rra
        jr c,t20a
t20b:
        jp $+3
        inc de
        in a,(c)
        rra
        jr nc,t20b
        ld (RESULTS+40),de
; [21] jr $+2
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t21a:
        jr $+2
        inc de
        in a,(c)
        rra
        jr c,t21a
t21b:
        jr $+2
        inc de
        in a,(c)
        rra
        jr nc,t21b
        ld (RESULTS+42),de
; [22] ex af,af' : ex af,af'
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t22a:
        ex af,af'
        ex af,af'
        inc de
        in a,(c)
        rra
        jr c,t22a
t22b:
        ex af,af'
        ex af,af'
        inc de
        in a,(c)
        rra
        jr nc,t22b
        ld (RESULTS+44),de
; [23] exx : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t23a:
        exx
        exx
        inc de
        in a,(c)
        rra
        jr c,t23a
t23b:
        exx
        exx
        inc de
        in a,(c)
        rra
        jr nc,t23b
        ld (RESULTS+46),de
; [24] neg
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t24a:
        neg
        inc de
        in a,(c)
        rra
        jr c,t24a
t24b:
        neg
        inc de
        in a,(c)
        rra
        jr nc,t24b
        ld (RESULTS+48),de
; [25] daa
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t25a:
        daa
        inc de
        in a,(c)
        rra
        jr c,t25a
t25b:
        daa
        inc de
        in a,(c)
        rra
        jr nc,t25b
        ld (RESULTS+50),de
; [26] ld a,i
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t26a:
        ld a,i
        inc de
        in a,(c)
        rra
        jr c,t26a
t26b:
        ld a,i
        inc de
        in a,(c)
        rra
        jr nc,t26b
        ld (RESULTS+52),de
; [27] ld a,r
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t27a:
        ld a,r
        inc de
        in a,(c)
        rra
        jr c,t27a
t27b:
        ld a,r
        inc de
        in a,(c)
        rra
        jr nc,t27b
        ld (RESULTS+54),de
; [28] ld i,a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t28a:
        ld i,a
        inc de
        in a,(c)
        rra
        jr c,t28a
t28b:
        ld i,a
        inc de
        in a,(c)
        rra
        jr nc,t28b
        ld (RESULTS+56),de
; [29] ld a,ixh
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t29a:
        ld a,ixh
        inc de
        in a,(c)
        rra
        jr c,t29a
t29b:
        ld a,ixh
        inc de
        in a,(c)
        rra
        jr nc,t29b
        ld (RESULTS+58),de
; [30] ld (0A000h),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t30a:
        ld (0A000h),a
        inc de
        in a,(c)
        rra
        jr c,t30a
t30b:
        ld (0A000h),a
        inc de
        in a,(c)
        rra
        jr nc,t30b
        ld (RESULTS+60),de
; [31] ld a,(0A000h)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t31a:
        ld a,(0A000h)
        inc de
        in a,(c)
        rra
        jr c,t31a
t31b:
        ld a,(0A000h)
        inc de
        in a,(c)
        rra
        jr nc,t31b
        ld (RESULTS+62),de
; [32] ld iy,(0A000h)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t32a:
        ld iy,(0A000h)
        inc de
        in a,(c)
        rra
        jr c,t32a
t32b:
        ld iy,(0A000h)
        inc de
        in a,(c)
        rra
        jr nc,t32b
        ld (RESULTS+64),de
; [33] ld (0A000h),iy
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t33a:
        ld (0A000h),iy
        inc de
        in a,(c)
        rra
        jr c,t33a
t33b:
        ld (0A000h),iy
        inc de
        in a,(c)
        rra
        jr nc,t33b
        ld (RESULTS+66),de
; [34] exx : ldi : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t34a:
        exx
        ldi
        exx
        inc de
        in a,(c)
        rra
        jr c,t34a
t34b:
        exx
        ldi
        exx
        inc de
        in a,(c)
        rra
        jr nc,t34b
        ld (RESULTS+68),de
; [35] exx : cpi : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t35a:
        exx
        cpi
        exx
        inc de
        in a,(c)
        rra
        jr c,t35a
t35b:
        exx
        cpi
        exx
        inc de
        in a,(c)
        rra
        jr nc,t35b
        ld (RESULTS+70),de
; [36] exx : ldd : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t36a:
        exx
        ldd
        exx
        inc de
        in a,(c)
        rra
        jr c,t36a
t36b:
        exx
        ldd
        exx
        inc de
        in a,(c)
        rra
        jr nc,t36b
        ld (RESULTS+72),de
; [37] rlca
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t37a:
        rlca
        inc de
        in a,(c)
        rra
        jr c,t37a
t37b:
        rlca
        inc de
        in a,(c)
        rra
        jr nc,t37b
        ld (RESULTS+74),de
; [38] rl (hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t38a:
        rl (hl)
        inc de
        in a,(c)
        rra
        jr c,t38a
t38b:
        rl (hl)
        inc de
        in a,(c)
        rra
        jr nc,t38b
        ld (RESULTS+76),de
; [39] ld sp,hl : ld sp,0BF00h
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t39a:
        ld sp,hl
        ld sp,0BF00h
        inc de
        in a,(c)
        rra
        jr c,t39a
t39b:
        ld sp,hl
        ld sp,0BF00h
        inc de
        in a,(c)
        rra
        jr nc,t39b
        ld (RESULTS+78),de
; [40] im 1
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t40a:
        im 1
        inc de
        in a,(c)
        rra
        jr c,t40a
t40b:
        im 1
        inc de
        in a,(c)
        rra
        jr nc,t40b
        ld (RESULTS+80),de
; [41] di
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t41a:
        di
        inc de
        in a,(c)
        rra
        jr c,t41a
t41b:
        di
        inc de
        in a,(c)
        rra
        jr nc,t41b
        ld (RESULTS+82),de
; [42] inc iy
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t42a:
        inc iy
        inc de
        in a,(c)
        rra
        jr c,t42a
t42b:
        inc iy
        inc de
        in a,(c)
        rra
        jr nc,t42b
        ld (RESULTS+84),de
; [43] add hl,de : sbc hl,de
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t43a:
        add hl,de
        sbc hl,de
        inc de
        in a,(c)
        rra
        jr c,t43a
t43b:
        add hl,de
        sbc hl,de
        inc de
        in a,(c)
        rra
        jr nc,t43b
        ld (RESULTS+86),de
; [44] exx : outi : inc b : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t44a:
        exx
        outi
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr c,t44a
t44b:
        exx
        outi
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr nc,t44b
        ld (RESULTS+88),de
; [45] exx : ini : inc b : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t45a:
        exx
        ini
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr c,t45a
t45b:
        exx
        ini
        inc b
        exx
        inc de
        in a,(c)
        rra
        jr nc,t45b
        ld (RESULTS+90),de
; [46] xor a : jr z,$+2
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t46a:
        xor a
        jr z,$+2
        inc de
        in a,(c)
        rra
        jr c,t46a
t46b:
        xor a
        jr z,$+2
        inc de
        in a,(c)
        rra
        jr nc,t46b
        ld (RESULTS+92),de
; [47] or 1 : jr z,$+2
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t47a:
        or 1
        jr z,$+2
        inc de
        in a,(c)
        rra
        jr c,t47a
t47b:
        or 1
        jr z,$+2
        inc de
        in a,(c)
        rra
        jr nc,t47b
        ld (RESULTS+94),de
; [48] xor a : jp z,$+3
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t48a:
        xor a
        jp z,$+3
        inc de
        in a,(c)
        rra
        jr c,t48a
t48b:
        xor a
        jp z,$+3
        inc de
        in a,(c)
        rra
        jr nc,t48b
        ld (RESULTS+96),de
; [49] or 1 : jp z,$+3
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t49a:
        or 1
        jp z,$+3
        inc de
        in a,(c)
        rra
        jr c,t49a
t49b:
        or 1
        jp z,$+3
        inc de
        in a,(c)
        rra
        jr nc,t49b
        ld (RESULTS+98),de
; [50] xor a : call z,sub_ret
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t50a:
        xor a
        call z,sub_ret
        inc de
        in a,(c)
        rra
        jr c,t50a
t50b:
        xor a
        call z,sub_ret
        inc de
        in a,(c)
        rra
        jr nc,t50b
        ld (RESULTS+100),de
; [51] or 1 : call z,sub_ret
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t51a:
        or 1
        call z,sub_ret
        inc de
        in a,(c)
        rra
        jr c,t51a
t51b:
        or 1
        call z,sub_ret
        inc de
        in a,(c)
        rra
        jr nc,t51b
        ld (RESULTS+102),de
; [52] call sub_retz_taken
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t52a:
        call sub_retz_taken
        inc de
        in a,(c)
        rra
        jr c,t52a
t52b:
        call sub_retz_taken
        inc de
        in a,(c)
        rra
        jr nc,t52b
        ld (RESULTS+104),de
; [53] call sub_retz_not
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t53a:
        call sub_retz_not
        inc de
        in a,(c)
        rra
        jr c,t53a
t53b:
        call sub_retz_not
        inc de
        in a,(c)
        rra
        jr nc,t53b
        ld (RESULTS+106),de
; [54] ld a,0F5h : out (0FFh),a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t54a:
        ld a,0F5h
        out (0FFh),a
        inc de
        in a,(c)
        rra
        jr c,t54a
t54b:
        ld a,0F5h
        out (0FFh),a
        inc de
        in a,(c)
        rra
        jr nc,t54b
        ld (RESULTS+108),de
; [55] ld a,0F5h : in a,(0FFh)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t55a:
        ld a,0F5h
        in a,(0FFh)
        inc de
        in a,(c)
        rra
        jr c,t55a
t55b:
        ld a,0F5h
        in a,(0FFh)
        inc de
        in a,(c)
        rra
        jr nc,t55b
        ld (RESULTS+110),de
; [56] exx : ld hl,09A00h : ld de,09C00h : ld bc,2 : ldir : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t56a:
        exx
        ld hl,09A00h
        ld de,09C00h
        ld bc,2
        ldir
        exx
        inc de
        in a,(c)
        rra
        jr c,t56a
t56b:
        exx
        ld hl,09A00h
        ld de,09C00h
        ld bc,2
        ldir
        exx
        inc de
        in a,(c)
        rra
        jr nc,t56b
        ld (RESULTS+112),de
; [57] exx : ld hl,09A10h : ld de,09C10h : ld bc,2 : lddr : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t57a:
        exx
        ld hl,09A10h
        ld de,09C10h
        ld bc,2
        lddr
        exx
        inc de
        in a,(c)
        rra
        jr c,t57a
t57b:
        exx
        ld hl,09A10h
        ld de,09C10h
        ld bc,2
        lddr
        exx
        inc de
        in a,(c)
        rra
        jr nc,t57b
        ld (RESULTS+114),de
; [58] exx : ld hl,09A00h : ld bc,2 : ld a,1 : cpir : exx
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t58a:
        exx
        ld hl,09A00h
        ld bc,2
        ld a,1
        cpir
        exx
        inc de
        in a,(c)
        rra
        jr c,t58a
t58b:
        exx
        ld hl,09A00h
        ld bc,2
        ld a,1
        cpir
        exx
        inc de
        in a,(c)
        rra
        jr nc,t58b
        ld (RESULTS+116),de
; [59] ld iy,$+6 : jp (iy)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t59a:
        ld iy,$+6
        jp (iy)
        inc de
        in a,(c)
        rra
        jr c,t59a
t59b:
        ld iy,$+6
        jp (iy)
        inc de
        in a,(c)
        rra
        jr nc,t59b
        ld (RESULTS+118),de
; [60] ex de,hl : ex de,hl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t60a:
        ex de,hl
        ex de,hl
        inc de
        in a,(c)
        rra
        jr c,t60a
t60b:
        ex de,hl
        ex de,hl
        inc de
        in a,(c)
        rra
        jr nc,t60b
        ld (RESULTS+120),de
; [61] push ix : pop ix
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t61a:
        push ix
        pop ix
        inc de
        in a,(c)
        rra
        jr c,t61a
t61b:
        push ix
        pop ix
        inc de
        in a,(c)
        rra
        jr nc,t61b
        ld (RESULTS+122),de
; [62] scf : ccf
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t62a:
        scf
        ccf
        inc de
        in a,(c)
        rra
        jr c,t62a
t62b:
        scf
        ccf
        inc de
        in a,(c)
        rra
        jr nc,t62b
        ld (RESULTS+124),de
; [63] cpl
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t63a:
        cpl
        inc de
        in a,(c)
        rra
        jr c,t63a
t63b:
        cpl
        inc de
        in a,(c)
        rra
        jr nc,t63b
        ld (RESULTS+126),de
; [64] rrd
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t64a:
        rrd
        inc de
        in a,(c)
        rra
        jr c,t64a
t64b:
        rrd
        inc de
        in a,(c)
        rra
        jr nc,t64b
        ld (RESULTS+128),de
; [65] sla (hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t65a:
        sla (hl)
        inc de
        in a,(c)
        rra
        jr c,t65a
t65b:
        sla (hl)
        inc de
        in a,(c)
        rra
        jr nc,t65b
        ld (RESULTS+130),de
; [66] bit 7,(hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t66a:
        bit 7,(hl)
        inc de
        in a,(c)
        rra
        jr c,t66a
t66b:
        bit 7,(hl)
        inc de
        in a,(c)
        rra
        jr nc,t66b
        ld (RESULTS+132),de
; [67] res 0,(hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t67a:
        res 0,(hl)
        inc de
        in a,(c)
        rra
        jr c,t67a
t67b:
        res 0,(hl)
        inc de
        in a,(c)
        rra
        jr nc,t67b
        ld (RESULTS+134),de
; [68] inc (ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t68a:
        inc (ix+0)
        inc de
        in a,(c)
        rra
        jr c,t68a
t68b:
        inc (ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t68b
        ld (RESULTS+136),de
; [69] add a,(ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t69a:
        add a,(ix+0)
        inc de
        in a,(c)
        rra
        jr c,t69a
t69b:
        add a,(ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t69b
        ld (RESULTS+138),de
; [70] sub (hl)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t70a:
        sub (hl)
        inc de
        in a,(c)
        rra
        jr c,t70a
t70b:
        sub (hl)
        inc de
        in a,(c)
        rra
        jr nc,t70b
        ld (RESULTS+140),de
; [71] adc a,1
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t71a:
        adc a,1
        inc de
        in a,(c)
        rra
        jr c,t71a
t71b:
        adc a,1
        inc de
        in a,(c)
        rra
        jr nc,t71b
        ld (RESULTS+142),de
; [72] ld (0A000h),hl : ld hl,(0A000h)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t72a:
        ld (0A000h),hl
        ld hl,(0A000h)
        inc de
        in a,(c)
        rra
        jr c,t72a
t72b:
        ld (0A000h),hl
        ld hl,(0A000h)
        inc de
        in a,(c)
        rra
        jr nc,t72b
        ld (RESULTS+144),de
; [73] ld (0A000h),de : ld de,(0A000h)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t73a:
        ld (0A000h),de
        ld de,(0A000h)
        inc de
        in a,(c)
        rra
        jr c,t73a
t73b:
        ld (0A000h),de
        ld de,(0A000h)
        inc de
        in a,(c)
        rra
        jr nc,t73b
        ld (RESULTS+146),de
; [74] ld sp,ix : ld sp,0BF00h
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t74a:
        ld sp,ix
        ld sp,0BF00h
        inc de
        in a,(c)
        rra
        jr c,t74a
t74b:
        ld sp,ix
        ld sp,0BF00h
        inc de
        in a,(c)
        rra
        jr nc,t74b
        ld (RESULTS+148),de
; [75] ex (sp),ix : ex (sp),ix
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t75a:
        ex (sp),ix
        ex (sp),ix
        inc de
        in a,(c)
        rra
        jr c,t75a
t75b:
        ex (sp),ix
        ex (sp),ix
        inc de
        in a,(c)
        rra
        jr nc,t75b
        ld (RESULTS+150),de
; [76] im 2 : im 1
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t76a:
        im 2
        im 1
        inc de
        in a,(c)
        rra
        jr c,t76a
t76b:
        im 2
        im 1
        inc de
        in a,(c)
        rra
        jr nc,t76b
        ld (RESULTS+152),de
; [77] ld r,a
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t77a:
        ld r,a
        inc de
        in a,(c)
        rra
        jr c,t77a
t77b:
        ld r,a
        inc de
        in a,(c)
        rra
        jr nc,t77b
        ld (RESULTS+154),de
; [78] rlc (ix+0)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t78a:
        rlc (ix+0)
        inc de
        in a,(c)
        rra
        jr c,t78a
t78b:
        rlc (ix+0)
        inc de
        in a,(c)
        rra
        jr nc,t78b
        ld (RESULTS+156),de
; [79] res 7,(ix+1)
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t79a:
        res 7,(ix+1)
        inc de
        in a,(c)
        rra
        jr c,t79a
t79b:
        res 7,(ix+1)
        inc de
        in a,(c)
        rra
        jr nc,t79b
        ld (RESULTS+158),de
; [80] ld b,(ix+0) : ld b,0F5h
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t80a:
        ld b,(ix+0)
        ld b,0F5h
        inc de
        in a,(c)
        rra
        jr c,t80a
t80b:
        ld b,(ix+0)
        ld b,0F5h
        inc de
        in a,(c)
        rra
        jr nc,t80b
        ld (RESULTS+160),de
; [81] ld (ix+2),b
        call wait_vsync
        ld bc,07F99h    ; MRER with bit 4: reset the interrupt counter
        out (c),c
        ei
        halt
        ld b,0F5h
        ld de,0
t81a:
        ld (ix+2),b
        inc de
        in a,(c)
        rra
        jr c,t81a
t81b:
        ld (ix+2),b
        inc de
        in a,(c)
        rra
        jr nc,t81b
        ld (RESULTS+162),de
done:
        jr done
